_target_: topobench.model.TBModel

model_name: topotune
model_domain: hypergraph
tune_gnn: GIN

feature_encoder:
  _target_: topobench.nn.encoders.${model.feature_encoder.encoder_name}
  encoder_name: AllCellFeatureEncoder
  in_channels: ${infer_in_channels:${dataset},${oc.select:transforms,null}} 
  out_channels: 32
  proj_dropout: 0.2
  selected_dimensions:
    - 0
    - 1
    - 2
    - 3
    - 4

backbone:
  _target_: topobench.nn.backbones.combinatorial.gccn.TopoTune
  GNN:
    _target_: torch_geometric.nn.${model.tune_gnn}
    in_channels: ${model.feature_encoder.out_channels}
    out_channels: ${model.feature_encoder.out_channels}
    hidden_channels: ${model.feature_encoder.out_channels}
    num_layers: 1
    dropout: 0.2
    norm: BatchNorm
  neighborhoods:
    - 4-down_incidence-4
  layers: 3
  use_edge_attr: false
  activation: relu

backbone_wrapper:
  _target_: topobench.nn.wrappers.combinatorial.TuneWrapper
  _partial_: true
  wrapper_name: TuneWrapper
  out_channels: ${model.feature_encoder.out_channels}
  num_cell_dimensions: ${infer_topotune_num_cell_dimensions:${oc.select:model.backbone.neighborhoods}}

readout:
  _target_: topobench.nn.readouts.${model.readout.readout_name}
  readout_name: PropagateSignalDown #  Use <NoReadOut> in case readout is not needed Options: PropagateSignalDown
  num_cell_dimensions: ${infer_topotune_num_cell_dimensions:${oc.select:model.backbone.neighborhoods}} # The highest order of cell dimensions to consider
  hidden_dim: ${model.feature_encoder.out_channels}
  out_channels: ${dataset.parameters.num_classes}
  task_level: ${dataset.parameters.task_level}
  pooling_type: sum
  hierarchical_propagation: false  # Whether to use hierarchical propagation or direct propagation
  ranks_to_propagate: [] # Ranks to propagate signals down from (only used if hierarchical_propagation is True)

# compile model for faster training with pytorch 2.0
compile: false
