_target_: topobench.transforms.data_transform.DataTransform
transform_name: "NeighborFeatureAggregation"   # fixed spelling
transform_type: "data manipulation"

selected_fields: ["edge_index"]              # or ["incidence_1", ...]
agg: ["mean","min","max"]                                 # "sum" | "mean" | "max"                          # e.g., "x_neighbor_mean" if "store"
x_field: "x"
num_hops: 3