# Dataset loader config
loader:
  _target_: topobench.data.loaders.D3D2MDatasetLoader
  parameters: 
    data_domain: cell
    data_type: topological
    data_name: 3D2M
    data_dir: ${paths.data_dir}/${dataset.loader.parameters.data_domain}/${dataset.loader.parameters.data_type}
    num_slices: null

# Dataset parameters
parameters:
  # Dataset parameters
  num_features: [3,3,3]
  num_classes: 2
  task: classification
  loss_type: cross_entropy
  monitor_metric: accuracy
  task_level: graph

#splits
split_params:
  learning_setting: inductive
  data_split_dir: ${paths.data_dir}/data_splits/${dataset.loader.parameters.data_name}
  data_seed: 0
  split_type: random #'k-fold' # either "k-fold" or "random" strategies
  k: 10 # for "k-fold" Cross-Validation
  train_prop: 0.5 # for "random" strategy splitting

# Dataloader parameters
dataloader_params:
  batch_size: 8 # Fixed
  num_workers: 1
  pin_memory: False