# Dataset loader config
loader:
  _target_: topobench.data.loaders.ChordonomiconDatasetLoader
  parameters: 
    data_domain: hypergraph
    data_type: chords
    data_name: chordonomicon
    data_dir: ${paths.data_dir}/${dataset.loader.parameters.data_domain}/${dataset.loader.parameters.data_type}
    version: all_scales  # options: ['single_scale', 'all_scales']

# Dataset parameters
parameters:
  num_features: 1
  num_classes: 1
  num_edge_features: 1
  num_node_features_single_scale: 12
  num_node_features_all_scales: 38
  task: regression
  loss_type: mse
  monitor_metric: mae
  task_level: edge

#splits
split_params:
  learning_setting: transductive
  data_seed: 0
  split_type: random #'k-fold' # either "k-fold" or "random" strategies
  k: 10 # for "k-fold" Cross-Validation
  train_prop: 0.9 # for "random" strategy splitting
  standardize: False
  data_split_dir: ${paths.data_dir}/data_splits/${dataset.loader.parameters.data_name}/${dataset.loader.parameters.version}

# Dataloader parameters
dataloader_params:
  batch_size: 1 # Fixed since transductive
  num_workers: 0
  pin_memory: False
