# Dataset loader config
loader:
  _target_: topobench.data.loaders.ConjugatedMoleculeDatasetLoader
  parameters: 
    data_domain: hypergraph
    data_type: conjugated_molecules
    data_name: OCELOTv1
    data_dir: ${paths.data_dir}/${dataset.loader.parameters.data_domain}/${dataset.loader.parameters.data_type}

# Dataset parameters
parameters:
  num_features: 9  # OGB atom features
  num_classes: 15  # 15 molecular property targets (regression)
  task: regression
  loss_type: mse
  monitor_metric: mae
  task_level: graph

#splits
split_params:
  learning_setting: inductive
  data_split_dir: ${paths.data_dir}/data_splits/${dataset.loader.parameters.data_name}
  data_seed: 0
  split_type: random  # OCELOTv1 doesn't have predefined splits
  k: 10  # for k-fold Cross-Validation
  train_prop: 0.8  # for random strategy splitting

# Dataloader parameters
dataloader_params:
  batch_size: 64
  num_workers: 4
  pin_memory: True
