# Dataset loader config - OPV train split (polymer task)
loader:
  _target_: topobench.data.loaders.ConjugatedMoleculeDatasetLoader
  parameters: 
    data_domain: hypergraph
    data_type: conjugated_molecules
    data_name: OPV
    split: train
    task: polymer  # Filters molecules with complete extrapolated properties
    target_col: ${dataset.parameters.target_col}
    data_dir: ${paths.data_dir}/${dataset.loader.parameters.data_domain}/${dataset.loader.parameters.data_type}

# Dataset parameters
parameters:
  num_features: 9  # OGB atom features
  num_classes: 1
  target_col: 0
  task: regression
  loss_type: mse
  monitor_metric: mae
  task_level: graph

#splits
split_params:
  learning_setting: inductive
  data_split_dir: ${paths.data_dir}/data_splits/${dataset.loader.parameters.data_name}
  data_seed: 0
  split_type: fixed
  k: 10
  train_prop: 0.8

# Dataloader parameters
dataloader_params:
  batch_size: 64
  num_workers: 4
  pin_memory: True
