# High School Contact Dataset
# Description: Sets of students in proximity (face-to-face contacts), where node
#              labels are classrooms.
# Source: https://www.cs.cornell.edu/~arb/data/contact-high-school-labeled/
# Statistics: 327 students | 7,818 contact groups | 9 classes
#             Mean/median hyperedge size: 2.3/2.0 | Max size: 5

# Dataset loader config
loader:
  _target_: topobench.data.loaders.CornellLabeledNodesDatasetLoader
  parameters: 
    data_domain: hypergraph
    data_type: cornell_labeled_nodes
    data_name: contact-high-school
    data_dir: ${paths.data_dir}/${dataset.loader.parameters.data_domain}/${dataset.loader.parameters.data_type}

# Dataset parameters
parameters:
  num_features: 1  # Simple constant features
  num_classes: 9  # Classrooms
  task: classification
  loss_type: cross_entropy
  monitor_metric: accuracy
  task_level: node

# Splits
split_params:
  learning_setting: transductive  # Single hypergraph, node classification task
  data_split_dir: ${paths.data_dir}/data_splits/${dataset.loader.parameters.data_name}
  data_seed: 0
  split_type: random
  k: 10  # for k-fold CV
  train_prop: 0.5  # for random split

# Dataloader parameters
dataloader_params:
  batch_size: 1  # Fixed for single hypergraph
  num_workers: 1
  pin_memory: False
