# Dataset loader config
loader:
  _target_: topobench.data.loaders.MIPLIBDatasetLoader
  parameters: 
    data_domain: hypergraph
    data_type: miplib
    data_name: benchmark
    data_dir: ${paths.data_dir}/${dataset.loader.parameters.data_domain}/${dataset.loader.parameters.data_type}

# Dataset parameters
parameters:
  num_features: 0
  num_classes: 0
  task: classification
  loss_type: cross_entropy
  monitor_metric: accuracy
  task_level: node

#splits
split_params:
  learning_setting: transductive
  data_split_dir: ${paths.data_dir}/data_splits/${dataset.loader.parameters.data_name}
  data_seed: 0
  split_type: random 
  k: 10 
  train_prop: 0.5 

# Dataloader parameters
dataloader_params:
  batch_size: 1 
  num_workers: 1
  pin_memory: False
