# Dataset loader config
loader:
  _target_: topobench.data.loaders.MIPLIBDatasetLoader
  parameters: 
    data_domain: hypergraph
    data_type: miplib
    data_name: benchmark
    data_dir: ${paths.data_dir}/${dataset.loader.parameters.data_domain}/${dataset.loader.parameters.data_type}
    task_level: graph

# Dataset parameters
parameters:
  num_features: 7  # 3 numerical + 4 one-hot encoded variable type features
  num_classes: 1  # Regression output (continuous value per variable)
  task: regression
  loss_type: mse  # Mean Squared Error for regression
  monitor_metric: mae  # Mean Absolute Error
  task_level: graph  # Predicting objective value for the graph

#splits
split_params:
  learning_setting: inductive
  data_split_dir: ${paths.data_dir}/data_splits/${dataset.loader.parameters.data_name}
  data_seed: 0
  split_type: random 
  k: 10 
  train_prop: 0.5 

# Dataloader parameters
dataloader_params:
  batch_size: 1 
  num_workers: 1
  pin_memory: False
