# Dataset loader config
loader:
  _target_: topobench.data.loaders.TwitterArlequinDatasetLoader
  parameters: 
    data_domain: hypergraph
    data_type: social
    data_name: TwitterArlequin
    data_dir: ${paths.data_dir}/${dataset.loader.parameters.data_domain}/${dataset.loader.parameters.data_type}
    # Hypergraph construction parameters
    cluster_level_posts: 1
    cluster_level_users: 0
    max_rank: 4
    cluster_seed: 42
    neighborhoods: ${oc.select:model.backbone.neighborhoods,null}

# Dataset parameters
parameters:
  num_features: [1024, 44, 1024, 1024, 44]
  num_classes: 44
  task: classification
  loss_type: cross_entropy
  monitor_metric: accuracy
  task_level: node

#splits
split_params:
  learning_setting: transductive
  data_split_dir: ${paths.data_dir}/data_splits/${dataset.loader.parameters.data_name}
  data_seed: 0
  split_type: random #'k-fold' # either "k-fold" or "random" strategies
  k: 10 # for "k-fold" Cross-Validation
  train_prop: 0.6 # for "random" strategy splitting

# Dataloader parameters
dataloader_params:
  batch_size: 1 # Fixed
  num_workers: 1
  pin_memory: False
