loader:
  _target_: topobench.data.loaders.MantraSimplicialDatasetLoader
  parameters: 
    data_domain: simplicial
    data_type: topological 
    data_name: MANTRA_betti_numbers
    data_dir: ${paths.data_dir}/${dataset.loader.parameters.data_domain}/${dataset.loader.parameters.data_type}
    manifold_dim: 2
    version: "v0.0.5"
    load_as_graph: False
    task_variable: "betti_numbers" # Options: ['name', 'genus', 'orientable'] To use 'torsion_coefficients', 'betti_numbers' fix multilabel multiclass issue
    model_domain: ${model.model_domain}
    neighborhoods: ${oc.select:model.backbone.neighborhoods,null}
    signed: True
    slice: False

# Data definition
parameters:
  # In the case of higher-order datasets we have multiple feature dimentions 
  num_features: [1,1,1]
  num_classes: 3 # In the case of 'betti_numbers', we have 3 types of betti numbers: [0, 1, 2], for  manifold_dim = 2
  num_betti_numbers: [2,7,2] # Number of betti numbers to predict, this is important for the regression task

  # Dataset parameters
  task: multivariate regression     # TODO: adapt pipeline to support multilabel classification
  loss_type: mse # TODO: adapt pipeline to support multilabel classification
  monitor_metric: loss # TODO: adapt pipeline to support multilabel classification
  task_level: graph 
  data_seed: 0
  preserve_edge_attr_if_lifted: False

#splits
split_params:
  learning_setting: inductive 
  data_split_dir: ${paths.data_dir}/data_splits/${dataset.loader.parameters.data_name}
  data_seed: 0
  split_type: stratified #'k-fold' # either "k-fold" or "random" strategies
  k: 10 # for "k-fold" Cross-Validation
  train_prop: 0.5 # for "random" strategy splitting

# Dataloader parameters
dataloader_params:
  batch_size: 256
  num_workers: 0
  pin_memory: False