_target_: topobench.model.TBModel

model_name: DeepSet
model_domain: pointcloud

feature_encoder:
  _target_: topobench.nn.encoders.${model.feature_encoder.encoder_name}
  encoder_name: AllCellFeatureEncoder
  in_channels: ${infer_in_channels:${dataset},${oc.select:transforms,null}}
  out_channels: 32
  proj_dropout: 0.0

backbone:
  _target_: torch.nn.Identity
  in_channels: ${model.feature_encoder.out_channels}
  hidden_channels: ${model.feature_encoder.out_channels}

backbone_wrapper:
  _target_: topobench.nn.wrappers.${model.backbone_wrapper.wrapper_name} 
  _partial_: true
  wrapper_name: PointcloudWrapper
  out_channels: ${model.feature_encoder.out_channels}
  num_cell_dimensions: ${infer_num_cell_dimensions:${oc.select:model.feature_encoder.selected_dimensions,null},${model.feature_encoder.in_channels}}

readout:
  _target_: topobench.nn.readouts.${model.readout.readout_name}
  readout_name: NoReadOut 
  hidden_dim: ${model.feature_encoder.out_channels}
  out_channels: ${dataset.parameters.num_classes}
  task_level: ${dataset.parameters.task_level}
  pooling_type: sum
  logits_linear_layer: false

# compile model for faster training with pytorch 2.0
compile: false