_target_: topobench.nn.wrappers.graph.sklearn.sklearn_wrappers.samplers.${model.backbone_wrapper.sampler.sampler_name}
sampler_name: GraphHopSampler
n_hops: 3 # Number of hops to sample from the graph, define during the run
drop: null # {"even", "odd", null} Whether to drop even or odd hops