# Lipophilicity Dataset
# Description: Experimental results of octanol/water distribution coefficient (logD at pH 7.4).
# Source: MoleculeNet benchmark collection
# Statistics: 4,200 graphs | ~27.0 nodes/graph | ~59.0 edges/graph | 9 features
# Task: Regression (lipophilicity prediction)

# Dataset loader config
loader:
  _target_: topobench.data.loaders.MoleculeNetDatasetLoader
  parameters: 
    data_domain: graph
    data_type: MoleculeNet
    data_name: Lipo
    data_dir: ${paths.data_dir}/${dataset.loader.parameters.data_domain}/${dataset.loader.parameters.data_type}

# Dataset parameters
parameters:
  num_features: 9
  num_classes: 1
  task: regression
  loss_type: mse
  monitor_metric: mae
  task_level: graph

# Splits
split_params:
  learning_setting: inductive
  data_split_dir: ${paths.data_dir}/data_splits/${dataset.loader.parameters.data_name}
  data_seed: 0
  split_type: random
  k: 10  # for k-fold CV
  train_prop: 0.8  # for random split

# Dataloader parameters
dataloader_params:
  batch_size: 64
  num_workers: 0
  pin_memory: False
