# Dataset loader config
loader:
  _target_: topobench.data.loaders.PPIDatasetLoader
  parameters: 
    data_domain: graph
    data_type: PPI
    data_name: PPI
    data_dir: ${paths.data_dir}/${dataset.loader.parameters.data_domain}/${dataset.loader.parameters.data_type}

# Dataset parameters
parameters:
  num_features: 50
  num_classes: 2
  task: classification
  loss_type: cross_entropy
  monitor_metric: auroc
  task_level: edge

#splits
split_params:
  learning_setting: inductive
  data_split_dir: ${paths.data_dir}/data_splits/${dataset.loader.parameters.data_name}
  data_seed: 0
  split_type: random #'k-fold' # either "k-fold" or "random" strategies
  k: 10 # for "k-fold" Cross-Validation
  train_prop: 0.5 # for "random" strategy splitting
  val_prop: 0.1
  test_prop: 0.1
  is_undirected: True
  neg_sampling_ratio: 1.0   # in val/test datasets
  neg_pos_ratio: 1.0    # in train dataset
  neg_sampling_method: sparse
  task_level: edge

# Dataloader parameters
dataloader_params:
  batch_size: 10
  num_workers: 0
  pin_memory: False
