# Semantic Dataset Configuration

# Dataset loader config
loader:
  _target_: topobench.data.loaders.SemanticDatasetLoader
  parameters: 
    data_domain: pointcloud
    data_type: semantic
    data_name: cifar10
    data_dir: ${paths.data_dir}/${dataset.loader.parameters.data_domain}/${dataset.loader.parameters.data_type}

# Dataset parameters
parameters:
  data_name: ${loader.parameters.data_name}
  models:
    - aimv2_1b_patch14_224.apple_pt
    - aimv2_1b_patch14_336.apple_pt
    - aimv2_1b_patch14_448.apple_pt

#splits
split_params:
  learning_setting: transductive
  data_split_dir: ${paths.data_dir}/data_splits/${dataset.loader.parameters.data_name}
  data_seed: 0
  split_type: random
  k: 10
  train_prop: 0.5

# Dataloader parameters
dataloader_params:
  batch_size: 1
  num_workers: 1
  pin_memory: False
